### ISSUE TITLE
TLS issue with passport-ldapauth

### ISSUE THREAD

**Issue by zhenwan** [osixia/docker-openldap#154]
Tried [passport-ldapauth](https://github.com/vesse/passport-ldapauth) provided sample code of "Active Directory over SSL example", always get following errors: 
Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1116:19)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

not sure if it is passport-ldapauth issue or it is docker-openldap issue. Hope someone knows how to solve this.

**Comment by zhenwan** [comment]
it seems this issue has nothing to do with passport-ldapauth. I tried ldapjs with following simple code, got the exact same error:

```
var ldap = require('ldapjs');
var client = ldap.createClient({
  url: 'ldaps://mycompany.com:636',
tlsOptions: {
            rejectUnauthorized: true,
            ca: [
              fs.readFileSync('/filepath/ldap.crt')
            ]
          }
});
```

**Comment by goeland86** [comment]
I have the same issue with TLS-enabled connections when trying to use Apache Directory Studio on the LDAP instance... plain connection works effortlessly, but TLS fails.
