### ISSUE TITLE
Why is this so complex ?

### ISSUE THREAD

**Issue by NargiT** [osixia/docker-openldap#230]
Hello,

I try to use your image in order to run an ldap inside docker container to simplify my e2e test. I am using spring-ldap-core 2.3.2.

When I run this on my local slapd (sudo apt-get install slapd) it works fine.

```java
	public static void main(String[] args) throws Exception {

		final LdapContextSource ldapContextSource = new LdapContextSource();
		ldapContextSource.setUrl("ldap://localhost:389");
		ldapContextSource.setUserDn("cn=admin,dc=example,dc=org");
		ldapContextSource.setPassword("admin");
		ldapContextSource.afterPropertiesSet();

		final LdapTemplate ldapTemplate = new LdapTemplate(ldapContextSource);
		ldapTemplate.afterPropertiesSet();
		final ContainerCriteria containerCriteria = LdapQueryBuilder.query()
				.base("dc=example,dc=org")
				.where("cn")
				.is("admin");
		ldapTemplate.authenticate(containerCriteria, "password");
	}
```

But with the docker image I have the following error. I checked with Apache Directory client and I can connect and verify the password. With Spring the admin password is correct because the search works, only authenticate always throw "LDAP: error code 49 - Invalid Credentials"

```
Exception in thread "main" org.springframework.ldap.AuthenticationException: [LDAP: error code 49 - Invalid Credentials]; nested exception is javax.naming.AuthenticationException: [LDAP: error code 49 - Invalid Credentials]
	at org.springframework.ldap.support.LdapUtils.convertLdapException(LdapUtils.java:191)
	at org.springframework.ldap.core.support.AbstractContextSource.createContext(AbstractContextSource.java:355)
	at org.springframework.ldap.core.support.AbstractContextSource.doGetContext(AbstractContextSource.java:139)
	at org.springframework.ldap.core.support.AbstractContextSource.getContext(AbstractContextSource.java:130)
	at org.springframework.ldap.core.LdapTemplate.authenticate(LdapTemplate.java:1454)
	at org.springframework.ldap.core.LdapTemplate.authenticate(LdapTemplate.java:1481)
	at org.springframework.ldap.core.LdapTemplate.authenticate(LdapTemplate.java:1510)
	at Scratch.main(scratch_2.java:31)
Caused by: javax.naming.AuthenticationException: [LDAP: error code 49 - Invalid Credentials]
	at com.sun.jndi.ldap.LdapCtx.mapErrorCode(LdapCtx.java:3154)
	at com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:3100)
	at com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:2886)
	at com.sun.jndi.ldap.LdapCtx.connect(LdapCtx.java:2800)
	at com.sun.jndi.ldap.LdapCtx.<init>(LdapCtx.java:319)
	at com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(LdapCtxFactory.java:192)
	at com.sun.jndi.ldap.LdapCtxFactory.getUsingURLs(LdapCtxFactory.java:210)
	at com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxInstance(LdapCtxFactory.java:153)
	at com.sun.jndi.ldap.LdapCtxFactory.getInitialContext(LdapCtxFactory.java:83)
	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:684)
	at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:313)
	at javax.naming.InitialContext.init(InitialContext.java:244)
	at javax.naming.ldap.InitialLdapContext.<init>(InitialLdapContext.java:154)
	at org.springframework.ldap.core.support.LdapContextSource.getDirContextInstance(LdapContextSource.java:42)
	at org.springframework.ldap.core.support.AbstractContextSource.createContext(AbstractContextSource.java:343)
	... 6 more
```

Looks like your image is doing some additional stuff that fail this code. I also write a similar snippet on a production ldap and it works like a charm.

Could you please help ? Didn't find anything in your readme.

**Comment by BertrandGouny** [comment]
Hello,
please check the credentials ...
`LDAP: error code 49 - Invalid Credentials`

this image do not allow anonymous bind and query.

For more help provide your container run options and the config used in your application.

**Comment by NargiT** [comment]
Hello,

I used ``docker run --rm=true -p 389:389 -p 636:636 --detach osixia/openldap:1.2.1``

What do you mean anonymous ? Sorry I am far to be an expert of ldap I start to work with it last week and already achieve a lot (IMHO). I just do not understand why there is a difference between the "basic" apt install slapd and this image.

**Comment by BertrandGouny** [comment]
This image was made to cover our specifics needs in the first place and extended by other lovely contributors.

The default admin password is **admin** not password. This line may cause the issue :
`ldapTemplate.authenticate(containerCriteria, "password");`

Also if you need no extra features environment variable `KEEP_EXISTING_CONFIG` can be set to `true`. 

Please refer to the README.md file for more information

**Comment by NargiT** [comment]
Sorry I reopen the issue because I would like to understand few things.

What does KEEP_EXISTING_CONFIG do ?

**Comment by BertrandGouny** [comment]
Can you be more specific? Wich part of the readme explanation must be improved? Wich part of the source code need to be explained?

**Comment by NargiT** [comment]
I would like to know what this project does more than the simple ``apt install slapd``.
The README is good it just miss information about what it does more compare the to the basic installation.

Does KEEP_EXISTING_CONFIG act as if I do `apt install slapd` ?

**Comment by NargiT** [comment]
Ok so I finally found my issue.

I read the change log and I saw that olcAccess were changed in version 1.2.1.
Even if I apply 
`
 olcAccess: to attrs=userPassword
  by self write
  by group.exact="cn=admin,dc=company,dc=com" write
  by anonymous auth
  by * none
`
It doesn't take in to account.

By using version 1.2.0 and my configuration I made it work.
