### ISSUE TITLE
copy-service fails

### ISSUE THREAD

**Issue by yuricus** [osixia/docker-openldap#276]
I'm running this image with --copy-service parameter, and it fails due to bad file in the image:

`docker run osixia/openldap-backup:1.2.2 --copy-service`

The output is: 
`*** CONTAINER_LOG_LEVEL = 3 (info)
*** Copy /container/service to /container/run/service
*** Killing all processes...
Traceback (most recent call last):
  File "/container/tool/run", line 890, in <module>
    main(args)
  File "/container/tool/run", line 775, in main
    setup_run_directories(args)
  File "/container/tool/run", line 376, in setup_run_directories
    copy_service_to_run_dir()
  File "/container/tool/run", line 442, in copy_service_to_run_dir
    shutil.copytree(IMPORT_SERVICE_DIR, RUN_SERVICE_DIR)
  File "/usr/lib/python2.7/shutil.py", line 208, in copytree
    raise Error, errors
shutil.Error: [('/container/service/:runit/download.sh', '/container/run/service/:runit/download.sh', "[Errno 2] No such file or directory: '/container/service/:runit/download.sh'")]`

If I launch the image without --copy-service and bash into container, download.sh  is in a strange condition:

`root@bdbd313b6953:/# ls /container/service/:runit/download.sh
ls: cannot access '/container/service/:runit/download.sh': No such file or directory`
and
`root@bdbd313b6953:/# ls -la /container/service/:runit/
ls: cannot access '/container/service/:runit/download.sh': No such file or directory
total 12
drwxrwxr-x 2 root root 4096 Jul 19  2017 .
drwxr-xr-x 1 root root 4096 Dec 26 13:57 ..
c????????? ? ?    ?       ?            ? download.sh`

Docker version 18.09.0, build 4d60db4, on Ubuntu.

Any ideas?
There's the same issue in other project with the same base image:
https://github.com/osixia/docker-phpLDAPadmin/issues/47

**Comment by Boldie** [comment]
I just have the same issue with docker version:
Docker version 18.06.1-ce, build e68fc7a running on Ubuntu 18.04.1 LTS

But with version:
Docker version 17.05.0-ce, build 89658be running on Ubuntu 16.04.5 LTS

everything works as expected. So it seems to be a problem with docker or with the OS.

**Comment by BertrandGouny** [comment]
Closing as part of repository issue cleanup. This report targets the legacy v1 image/configuration, which is no longer maintained here. Version 2.6.10 is available as an alpha image (`osixia/openldap:2.6.10-alpha`) for testing; please retest with that image and open a new issue with an up-to-date reproduction if the problem still applies.
